extensions:
  - file://BASE_PATH/geminiFileUploadInJs.mjs:geminiUploadExtension
  - file://BASE_PATH/geminiFileUploadInJs.mjs:testsRepeat
  - file://BASE_PATH/geminiFileUploadInJs.mjs:replaceCurlyBrackets
  - file://BASE_PATH/geminiFileUploadInJs.mjs:returnCurlyBrackets
  - file://BASE_PATH/geminiFileUploadInJs.mjs:finalCleanup
  - file://BASE_PATH/geminiFileUploadInJs.mjs:addVars
  - file://BASE_PATH/geminiFileUploadInJs.mjs:addVarsBeforeEach

#prompts:
#  - BASE_PATH/motion/prompts/performance_summary.txt
#  - BASE_PATH/motion/prompts/dara-summary.txt

prompts:
  - '[[promptText]]'
providers:
  - id: openai:o1
#  - id: google:gemini-1.5-flash
#    config:
#      temperature: 1.0


tests:
  - vars:
      itemName: 'MAIN'
      spendState: 'Holding'
      launchDate: '2023-01-01'
      spend: '1000'
      roas: '10'
      unique_click_to_purchase_ratio: '0.5'
      ctr: '0.5'
      cpm: '0.5'
      motion_capture_attention: '0.5'
      motion_hold_attention: '0.5'
      motion_bring_to_site: '0.5'
      motion_drive_conversions: '0.5'
      summary: file://BASE_PATH/motion/main_creative_summary.txt
      promptText: file://BASE_PATH/motion/prompts/performance_summary.txt
    options:
      storeOutputAs: performanceStatsSummary
  - vars:
      itemName: 'MAIN'
      summary: file://BASE_PATH/motion/main_creative_summary.txt
      promptText: file://BASE_PATH/motion/prompts/dara-summary.txt
    options:
      storeOutputAs: creativeChecklist

  - vars:
      itemName: 'SIMILAR_ONE'
      spendState: 'Declining'
      launchDate: '2024-02-12'
      spend: '2000'
      roas: '5'
      unique_click_to_purchase_ratio: '0.1'
      ctr: '0.1'
      cpm: '0.1'
      motion_capture_attention: '0.1'
      motion_hold_attention: '0.1'
      motion_bring_to_site: '0.1'
      motion_drive_conversions: '0.1'
      summary: file://BASE_PATH/motion/similar_one_creative_summary.txt
      promptText: file://BASE_PATH/motion/prompts/performance_summary.txt
    options:
      storeOutputAs: performanceStatsSummary
  - vars:
      itemName: 'SIMILAR_ONE'
      summary: file://BASE_PATH/motion/similar_one_creative_summary.txt
      promptText: file://BASE_PATH/motion/prompts/dara-summary.txt
    options:
      storeOutputAs: creativeChecklist
  - vars:
      itemName: 'MAIN'
      useCollectedPreviousOutputs: 'true'
      mainSummary: file://BASE_PATH/motion/main_creative_summary.txt
      similarOneSummary: file://BASE_PATH/motion/similar_one_creative_summary.txt
      promptText: file://BASE_PATH/motion/prompts/report.txt
    options:
      storeOutputAs: creativeReport
  - vars:
      itemName: 'MAIN'
      useCollectedPreviousOutputs: 'true'
      mainSummary: file://BASE_PATH/motion/main_creative_summary.txt
      promptText: file://BASE_PATH/motion/prompts/next-steps.txt
